runtime: python311

env_variables:
  # Environment Configuration
  ENVIRONMENT: production
  DEBUG: false
  
  # API Configuration
  API_V1_STR: /api/v1
  PROJECT_NAME: VeriTrueAI2.0
  LOG_LEVEL: INFO
  
  # Non-sensitive configuration
  GEMINI_MODEL: gemini-pro
  GOOGLE_CLOUD_PROJECT_ID: veritrueai
  MAX_UPLOAD_SIZE: 50MB
  UPLOAD_DIR: /tmp/uploads
  SEARCH_ENGINE_ID: d3a39005958a34dac
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

# Sensitive data from Secret Manager
beta_settings:
  cloud_sql_instances: veritrueai:us-central1:veritrue-db

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /uploads/.*
  static_dir: uploads
  secure: always

- url: /.*
  script: auto
  secure: always