runtime: python311

env_variables:
  # Environment Configuration
  ENVIRONMENT: production
  DEBUG: false
  
  # API Configuration
  API_V1_STR: /api/v1
  PROJECT_NAME: VeriTrueAI2.0
  LOG_LEVEL: INFO
  
  # Database Configuration (Cloud SQL)
  DATABASE_URL: postgresql://username:password@/database_name?host=/cloudsql/project:region:instance
  
  # Redis Configuration (Memorystore)
  REDIS_URL: redis://redis-instance-ip:6379/0
  
  # OpenAI Configuration
  OPENAI_API_KEY: your_openai_api_key_here
  
  # Google Cloud Configuration
  GOOGLE_CLOUD_PROJECT_ID: your_project_id
  
  # File Upload Configuration
  MAX_UPLOAD_SIZE: 50MB
  UPLOAD_DIR: /tmp/uploads
  
  # Web Search Configuration
  SEARCH_API_KEY: your_search_api_key
  SEARCH_ENGINE_ID: your_search_engine_id
  
  # Security
  SECRET_KEY: your_production_secret_key_here
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /uploads/.*
  static_dir: uploads
  secure: always

- url: /.*
  script: auto
  secure: always